### PR TITLE
upgrade cipher used

### LINKED ISSUE #15: Default Cipher is Insecure
The default cipher this installs is vulnerable to SWEET32 attacks.  We should update it to use a more secure cipher.

### PR DESCRIPTION
**Pull request by sairez**
This would fix #15 and address issues customers have raised

### CODE REVIEW

**Comment by emalloy** [comment]
:+1:

**Comment by sairez** [comment]
Great question @ejether! I'm attempting to confirm whether or not this means that user .ovpn profiles will be updated and require profiles to be re-distributed. I'll report back

**Comment by emalloy** [comment]
@sairez @ejether Had a test run with this last Friday night for node (which is using this updated role currently). 

1. the old ovpn profiles and certs I had did _not_ work.
2. I resolved this by re-downloading the profile + cert bundle from s3 and I was able to connect.

**Comment by geojaz** [comment]
lgtm. thanks @sairez

**Pull request merged**
